num1 = int(input(' Введите 1 число '))
num2 = int(input(' Введите 2 число '))
num3 = int(input(' Введите 3 число '))
num4 = int(input(' Введите 4 число '))
num5 = int(input(' Введите 5 число '))
num6 = int(input(' Введите 6 число '))
num7 = int(input(' Введите 7 число '))
num8 = int(input(' Введите 8 число '))
num9 = int(input(' Введите 9 число '))
num10 = int(input(' Введите 10 число '))
a = [num1,num2,num3,num4,num5,num6,num7,num8,num9,num10 ]
b = min(a)
c= max(a)
print ('Из всех введенных чисел: ' , a , 'наименьшее - ' , b , 'наибольшее - ', c )